name: Deploy AWS

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Install dependencies
      run: dotnet restore ./ApiAws/ApiAws/ApiAws.csproj
    
    - name: Build
      run: dotnet build ./ApiAws/ApiAws/ApiAws.csproj --configuration Release --no-restore
   
    - name: Publish
      run: dotnet publish ./ApiAws/ApiAws/ApiAws.csproj -c Release -o '${{ github.workspace }}/out'
  
    - name: Zip Package
      run: |
        cd ${{ github.workspace }}/out 
        zip -r ${{ github.workspace }}/out.zip *
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v13
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: safra-backend-test
        environment_name: Safrabackendtest-env
        region: ${{ secrets.AWS_REGION }}
        version_label: ${{ github.run_id }}
        version_description: ${{ github.sha }}
        deployment_package: ${{ github.workspace }}/out.zip
